### ISSUE TITLE
$_SERVER['HTTP_USER_AGENT'] index causing an error notice.

### ISSUE THREAD

**Issue by kotecky** [craigrodway/LoginPersist#1]
Processwire issues the following notice: 
`PHP Notice: Undefined index: HTTP_USER_AGENT in /mnt/data/accounts/l/luxoc/data/www/luxoc_pw3.0/site/assets/cache/FileCompiler/site/modules/LoginPersist/LoginPersist.module:508`
It is possible that not all server environments have the index HTTP_USER_AGENT set. As such it should be checked before being used.

**Comment by craigrodway** [comment]
Thanks @kotecky, you're right! This should definitely be checked before accessing/referring to the variable.

**Comment by teppokoivula** [comment]
@craigrodway, ping – here's another issue that could be fixed by merging a PR :)

**Comment by craigrodway** [comment]
@teppokoivula Thanks!

I've made some general updates and fixed this issue as well in the https://github.com/craigrodway/LoginPersist/tree/develop branch, provisionally version 2.

Please try it out and let me know if it fixed/breaks anything for you!

**Comment by spackmat** [comment]
Just came across that notice, where I use the ProcessWire-API in a CLI script. Obviously there is no HTTP_USER_AGENT present. I tried the current develop branch that seems to work and removes that notice. So maybe a new release could be done?

**Comment by craigrodway** [comment]
Hi @spackmat, thanks for the nudge! I've actually been working on another feature request (#4) for the last couple of days, and a release is imminent :)

**Comment by craigrodway** [comment]
Now fixed in 2.1.0! 🎉
