### ISSUE TITLE
Processwire update process keeps loading module v2.1.2.zip

### ISSUE THREAD

**Issue by JavonX** [craigrodway/LoginPersist#11]
Hi, thanks for the update.

When I try to update the module through processwire using the "check for updates" function in the module information, it detects a new version that I can install, but the file it downloads is still the old version:

ProcessModuleInstall: Downloaded ZIP file: https://github.com/craigrodway/LoginPersist/archive/refs/tags/v2.1.2.zip (21910 bytes) [+11](http://localhost/processwire/module/download/#)

**Comment by craigrodway** [comment]
Sorry about that! I thought the PW Modules Directory would automatically update the Zip URL from the GitHub release, but I had to change it manually. Please try again now.

**Comment by JavonX** [comment]
it works now, thanks
