### ISSUE TITLE
Cookie length is always 7 days. WireInputDataCookie expects "expire" option and not "expires"

### ISSUE THREAD

**Issue by hiboudev** [craigrodway/LoginPersist#13]
In method persist(), this code:
```
$this->wire('input')->cookie->set($this->get('cookieName'), $value, [
  'expires' => $expires,
  'path' => '/',
  'domain' => null,
  'secure' => false,
  'httponly' => true,
]);
```

You are using "expires" as option key.

But in WireInputDataCookie->setCookie(), it expects "expire", so the cookie length is ALWAYS 7 days (a default value coming from somewhere).

```
if(!empty($options['expire'])) {
  if(is_string($options['expire']) && !ctype_digit($options['expire'])) {
    $expires = strtotime($options['expire']);
  } else {
    $expires = (int) $options['expire'];
  }
}
```

There are 3 occurrences of "expires" to fix in your class, that means there's more bugs, and now I understand why one of my customer is complaining to sometimes lose his session while using the site.

https://processwire.com/api/ref/wire-input-data-cookie/set/

**Comment by craigrodway** [comment]
Thanks for reporting this; it was due to the switch from native PHP to PW's cookie setting methods. Resolved in 2.3.0.
