### ISSUE TITLE
$user not found

### ISSUE THREAD

**Issue by somatonic** [craigrodway/LoginPersist#2]
I'm trying to use this module. 

It seems to be working kinda (not sure yet and haven't looked and tested throughout), but got a error that the $user var is not defined.

https://github.com/craigrodway/LoginPersist/blob/master/LoginPersist.module#L374

I'm not sure why it got there anyway as it should have just logged in the user.  I'm not sure if session Fingerprint is really working.

Removing the wire cookies in browser manually seems to work though.

**Comment by craigrodway** [comment]
Hi!

You're right - it's not defined for use in that part of the `if` statement. It's probably left over from a previous refector where it _was_ used. I think it was a precaution against the keys not being validated.

This module is a bit old now and I haven't used it for a long time, so could probably do with an update, at the minimum! There could even be a better way of achieving this with newer versions of PW.

**Comment by teppokoivula** [comment]
@craigrodway, just a heads-up that this issue is still open. Any chance of getting it fixed? Thanks in advance! :)

What @tobaco did in the commit (+ PR) referenced above is how I fixed this locally as well – basically $cookie->user instead of $user. Seems like a trivial thing, but I might be missing something important. Also it would be great to have the fix in the official repository.

**Comment by craigrodway** [comment]
@teppokoivula Thanks! I had sort of forgotten about this, amongst other project work...

I've made some general updates and fixed this issue in the https://github.com/craigrodway/LoginPersist/tree/develop branch, provisionally version 2.

Please try it out and let me know if it fixed/breaks anything for you!

**Comment by teppokoivula** [comment]
Thanks @craigrodway – I'll give this a try and let you know if there are any issues with it :)

**Comment by craigrodway** [comment]
This is finally fixed in 2.1.0! 🎉
