### ISSUE TITLE
Feature request: invalid roles

### ISSUE THREAD

**Issue by Toutouwai** [craigrodway/LoginPersist#4]
There is a config setting for valid roles, but it would be great if there was also a setting for invalid roles.

I'd like to use persistent logins for front-end users with the "member" role but not for admin users (superusers, etc). But my admin users have multiple roles including the member role. Having an "Invalid roles" setting would allow for setups like this.

Thanks for considering.

**Comment by craigrodway** [comment]
Hi! That sounds like a good suggestion, and seems relatively easy enough to add. I'll look at this soon!

**Comment by Toutouwai** [comment]
Thanks!

**Comment by craigrodway** [comment]
This has been added in 2.1.0! 🎉
