### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by teppokoivula** [craigrodway/LoginPersist#5]
Hey @craigrodway,

We've been using this module for a while and it's been working splendidly. So first of all: thank you! :)

Now, one thing I'd love to have would be the ability to install the module via Composer. Just in case I'll outline the recommended steps for ProcessWire modules here — in case it's all old news to you feel free to ignore them.

1. Add a composer.json file, here's a minimal example:

```
{
    "name": "craigrodway/login-persist",
    "type": "pw-module",
    "require": {
        "wireframe-framework/processwire-composer-installer": "^1.0.0"
    }
}
```

*(Note: Packagist complains if the author name is not all lowercase, and the installer plugin in turn expects to see dash as a word separator in the package name so that the directory for login-persist becomes LoginPersist.)*

2. Add the package to packagist.org: https://packagist.org/packages/submit

... and that's it, since you're already using tags here. Though you may also want to set up git hooks between Packagist and GitHub (Packagist has guide for this if you haven't done it before) so that the version numbers get automatically updated there :)

Thanks in advance for considering this!

**Comment by craigrodway** [comment]
Hi Teppo!

Happy to hear that you've been using it and that it's (still?!) working well for you! I know I haven't done any updates for a long time, but if it isn't broken, then there's nothing to fix :) 

I'm more than happy to add Composer support, and thanks for the heads-up around how to do it for PW. I knew some extra 'stuff' was needed (compared to regular PHP libraries) but didn't know exactly what, so that info is useful.

**Comment by craigrodway** [comment]
👋 Me again.

Here you go: https://packagist.org/packages/craigrodway/login-persist

Please give that a whirl and let me know if it works or breaks! :)

**Comment by teppokoivula** [comment]
Thanks, @craigrodway! Just gave it a try and composer install works as expected. I'll go ahead and close this issue.

Also: agreed — no need to fix what already works :D

**Comment by craigrodway** [comment]
Brilliant, thanks for letting me know! Enjoy 😃
