### ISSUE TITLE
PHP Notice: Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by adrianbj** [craigrodway/LoginPersist#6]
The new version has this error. Remember that HTTP_USER_AGENT is optional so you need to do an `isset` check on it first, just like the core PW `getFingerprint()` method does.

Thanks.

**Comment by craigrodway** [comment]
Hi! Can you double-check which version you're running please and where the error is coming from exactly?

The current master, at 2.1.2, uses PW's built-in fingerprint method and doesn't directly access any globals like HTTP_USER_AGENT.

**Comment by adrianbj** [comment]
Hi @craigrodway - that's really strange. I was running 2.1.0 but then the PW Upgrades noted there was a new version - I upgraded and it somehow installed 1.0.0

I just tried again and despite it reporting 2.1.2 as the new version, it keeps installing 1.0.0. I manually upgraded so I am sure the issue will be gone now.

I suppose this is a bug in the PW Upgrades module.

**Comment by craigrodway** [comment]
Hmm. Very odd that it downgraded!

I've just noticed that 2.1.1 and 2.1.2 don't have "official" releases in GitHub at this time - perhaps that confused PW version checker?

Glad you've got it sorted but I'll go ahead and make the releases official in GitHub anyway.
