### ISSUE TITLE
Variable $user is not defined

### ISSUE THREAD

**Issue by Statter** [craigrodway/LoginPersist#7]
When trying to validate non-existent persistent cookie, the next code fires (lines 371-375):

 else {
                // Failure! Invalidate all user's persistent login data
                $this->destroyLogins($user);
 }

I believe, it should be: $this->destroyLogins($cookie->user);
Not just: $this->destroyLogins($user);

$user variable has not been defined in the scoop of the function

**Comment by craigrodway** [comment]
This has now been fixed, thanks.
