### ISSUE TITLE
Module latest version link is outdated in PW modules. (v1.0.0 instead of latest)

### ISSUE THREAD

**Issue by ArneAmeye** [craigrodway/LoginPersist#8]
It seems that the latest version links to the V1.0.0 zip file. Both from updating within module as the PW module page download button. Which means our module gets downgraded when using the updater links.
I've downloaded the correct zip file from Github for now.

**Comment by craigrodway** [comment]
Hi @ArneAmeye, thanks for letting me know. I've updated the listing in the Modules Directory to point to the latest release :)

**Comment by ArneAmeye** [comment]
@craigrodway Thanks, that was fast :)
