### ISSUE TITLE
setcookie with null as domain value is deprecated

### ISSUE THREAD

**Issue by poljpocket** [craigrodway/LoginPersist#9]
In PHP's `setcookie` function, the 5th parameter `domain` with `null` as value is deprecated at least on newer versions of PHP (tested on 8.1.11). This results in a warning and may break login functionality.

**Comment by snobjorn** [comment]
When logging out of ProcessWire, this error now appears:

`
Fatal error: Uncaught ValueError: setcookie(): Argument #1 ($name) cannot be empty in site/modules/LoginPersist/LoginPersist.module:133
`

Running ProcessWire on a PHP 8.1 server.

**Comment by poljpocket** [comment]
@snobjorn I believe this is related to the deprecation as well. My PR #10 uses PW's native cookie functions and should not have this problem.

**Comment by poljpocket** [comment]
@snobjorn if you want, you can test with my fork where the changes mentioned are applied: https://github.com/poljpocket/processwire-module-loginpersist

**Comment by JavonX** [comment]
I get the following messages:

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vhosts/httpdocs/wire/core/WireInput.php on line 371

Warning: Undefined array key 1 in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 471

Warning: Undefined array key 2 in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 471

Deprecated: setcookie(): Passing null to parameter #1 ($name) of type string is deprecated in /var/www/vhosts/httpdocs/site/modules/LoginPersist/LoginPersist.module on line 133

On PHP 8.2.5.
Not sure if the first core message is related to the loginPersit messages

**Comment by craigrodway** [comment]
Thanks for the reports and contributions, this has now been fixed - https://github.com/craigrodway/LoginPersist/releases/tag/v2.2.0
